### ISSUE TITLE
Provide enhanced large screen display

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#122]
**Summary:** 

Currently, any large screen devices (e.g., tablets) will use the `activity_main_large_screen` layout, which as of v3.0.0 no longer has the overflow menu button to access things like Settings, etc. (these were all moved to the navigation drawer).

I need to update the above layout to use the navigation drawer as well, and figure out how the navigation drawer logic works with this.

**Steps to reproduce:** 

Start the app on a tablet

**Expected behavior:** 

Give me access to all the features of the navigation drawer, but show all 3 fragments on the screen at once (side-by-side)

**Observed behavior:** 

~~I haven't tested, but I'm assuming it shows all 3 fragments without showing the navigation drawer (or it just crashes because it tries to access the navigation drawer, which doesn't exist using the large screen layout)~~

Yup, on a Pixel C emulator it crashes:

~~~
 FATAL EXCEPTION: main
   Process: com.android.gpstest, PID: 5949
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.gpstest/com.android.gpstest.GpsTestActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.gpstest.NavigationDrawerFragment.setUp(int, android.support.v4.widget.DrawerLayout)' on a null object reference
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	   at android.app.ActivityThread.-wrap11(Unknown Source:0)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	   at android.os.Handler.dispatchMessage(Handler.java:105)
	   at android.os.Looper.loop(Looper.java:164)
	   at android.app.ActivityThread.main(ActivityThread.java:6541)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.gpstest.NavigationDrawerFragment.setUp(int, android.support.v4.widget.DrawerLayout)' on a null object reference
	   at com.android.gpstest.GpsTestActivity.setupNavigationDrawer(GpsTestActivity.java:306)
	   at com.android.gpstest.GpsTestActivity.onCreate(GpsTestActivity.java:227)
	   at android.app.Activity.performCreate(Activity.java:6975)
	   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
~~~

**Device and Android version:** 

Pixel C emulator

**Comment by barbeau** [comment]
I've implemented a temporary workaround for this in https://github.com/barbeau/gpstest/commit/b30c0882135cdb6c8533fa46bc331f179e550954 so that large screen devices use the same layout as normal sized devices - this prevents the app from crashing on large screen devices.  Still need to implement a new layout for large screen devices that works with the navigation drawer fragment.
