### ISSUE TITLE
Android N crash - ArrayIndexOutOfBoundsException, CalledFromWrongThreadException

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#64]
**Summary:** 

When the app starts receiving GnssStatus updates on Android N, the app crashes with:

~~~
10-14 11:11:34.122 21959-21959/? E/AndroidRuntime: FATAL EXCEPTION: main
		   Process: com.android.gpstest, PID: 21959
		   java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
			   at com.android.gpstest.GpsStatusFragment.updateGnssStatus(GpsStatusFragment.java:349)
			   at com.android.gpstest.GpsStatusFragment.onSatelliteStatusChanged(GpsStatusFragment.java:270)
			   at com.android.gpstest.GpsTestActivity$1.onSatelliteStatusChanged(GpsTestActivity.java:352)
			   at android.location.LocationManager$GnssStatusListenerTransport$GnssHandler.handleMessage(LocationManager.java:1434)
			   at android.os.Handler.dispatchMessage(Handler.java:102)
			   at android.os.Looper.loop(Looper.java:154)
			   at android.app.ActivityThread.main(ActivityThread.java:6077)
			   at java.lang.reflect.Method.invoke(Native Method)
			   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
			   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-14 11:11:34.131 21959-21971/? W/Binder: Binder call failed.
   android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	   at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6855)
	   at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1075)
	   at android.view.ViewGroup.invalidateChild(ViewGroup.java:5242)
	   at android.view.View.invalidateInternal(View.java:13573)
	   at android.view.View.invalidate(View.java:13537)
	   at android.view.View.invalidate(View.java:13521)
	   at com.android.gpstest.GpsSkyFragment$GpsSkyView.setGnssMeasurementEvent(GpsSkyFragment.java:344)
	   at com.android.gpstest.GpsSkyFragment.onGnssMeasurementsReceived(GpsSkyFragment.java:137)
	   at com.android.gpstest.GpsTestActivity$2.onGnssMeasurementsReceived(GpsTestActivity.java:368)
	   at android.location.GnssMeasurementCallbackTransport$ListenerTransport$1.execute(GnssMeasurementCallbackTransport.java:58)
	   at android.location.GnssMeasurementCallbackTransport$ListenerTransport$1.execute(GnssMeasurementCallbackTransport.java:56)
	   at android.location.LocalListenerHelper.executeOperation(LocalListenerHelper.java:104)
	   at android.location.LocalListenerHelper.foreach(LocalListenerHelper.java:118)
	   at android.location.GnssMeasurementCallbackTransport$ListenerTransport.onGnssMeasurementsReceived(GnssMeasurementCallbackTransport.java:61)
	   at android.location.IGnssMeasurementsListener$Stub.onTransact(IGnssMeasurementsListener.java:58)
	   at android.os.Binder.execTransact(Binder.java:565)
~~~

**Steps to reproduce:** 

Start app and wait for sat status update

**Expected behavior:** 

Not crash and show sat status

**Observed behavior:** 

Crash

**Device and Android version:** 

Nexus 5X with Android 7.0

**Comment by barbeau** [comment]
Same array size issue needs to be fixed in `GpsSkyFragment` as well.
