### ISSUE TITLE
IllegalStateException when updating status

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#85]
**Summary:** 

I saw a crash today with this in the log:

~~~
Process: com.android.gpstest, PID: 15575
   java.lang.IllegalStateException: Fragment GpsStatusFragment{f97116d} not attached to Activity
	   at android.support.v4.app.Fragment.getResources(Fragment.java:648)
	   at android.support.v4.app.Fragment.getString(Fragment.java:683)
	   at com.android.gpstest.GpsStatusFragment.updateLegacyStatus(GpsStatusFragment.java:409)
	   at com.android.gpstest.GpsStatusFragment.onGpsStatusChanged(GpsStatusFragment.java:251)
	   at com.android.gpstest.GpsTestActivity$3.onGpsStatusChanged(GpsTestActivity.java:461)
	   at android.location.LocationManager$GnssStatusListenerTransport$1.onSatelliteStatusChanged(LocationManager.java:1515)
	   at android.location.LocationManager$GnssStatusListenerTransport$GnssHandler.handleMessage(LocationManager.java:1463)
	   at android.os.Handler.dispatchMessage(Handler.java:102)
	   at android.os.Looper.loop(Looper.java:154)
	   at android.app.ActivityThread.main(ActivityThread.java:6247)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
~~~

**Steps to reproduce:** 

Unsure

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

LG G5 w/ Android 7.0

**Comment by barbeau** [comment]
Looking at the Android Developer Console, there are a few more reports of this too - it happens when we try to reference the `getString()` method within the Fragment, which tries to get the Activity it's attached to, and if it's not attached we then get the `IllegalStateException`.  One fix is to use the `Resources` reference that we grab in the Fragment `onCreateView()` - this is how other areas of the app deal with it.  Another solution is to check `getActivity()` to see if it's null, as well as check `isAdded()` to see if the Fragment is attached to the Activity.

~~~
java.lang.IllegalStateException: 
  at android.support.v4.app.Fragment.getResources(Fragment.java:648)
  at android.support.v4.app.Fragment.getString(Fragment.java:683)
  at com.android.gpstest.GpsStatusFragment.onLocationChanged(GpsStatusFragment.java:98)
  at com.android.gpstest.GpsTestActivity.onLocationChanged(GpsTestActivity.java:788)
  at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
  at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java:0)
  at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
~~~

**Comment by barbeau** [comment]
~~~
java.lang.IllegalStateException: 
  at android.support.v4.app.Fragment.getResources(Fragment.java:648)
  at android.support.v4.app.Fragment.getString(Fragment.java:683)
  at com.android.gpstest.GpsStatusFragment.onNmeaMessage(GpsStatusFragment.java:290)
  at com.android.gpstest.GpsTestActivity$5.onNmeaReceived(GpsTestActivity.java:508)
  at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1474)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5349)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
~~~
